In [399]:
import numpy as np
import pandas as pd

In [400]:
def network_structure(structure):
    layers = len(structure)
    #biases = [np.random.rand(y,1) for y in structure[1:]]
    weights = [np.random.rand(x,y) for y,x in zip(structure[:-1],structure[1:]) ]
    return layers,weights   
        

In [401]:
def sigmoid(x):
    return 1.0/(1.0+np.exp(-x))

In [402]:
def sigmoid_diff(x):
    return sigmoid(x)*(1-sigmoid(x))

In [403]:
def feedforward(x_input,weights):
    z = [0]*layers
    z[0] = x_input
    for i in range(1,layers):
        z[i] = (sigmoid(np.dot(weights[i-1],z[i-1])))
    return z        

In [404]:
def cost_derivative(output_activations,y,m):
    return np.sum((1/m)*np.abs(y-output_activations))            

In [413]:
def backprop(y,m,z,weights,lr):
    grad_cw = [0]*(layers-1)
    prod_1 = 1
    for i in range(layers-1,0,-1):
        prod = 1
        if(prod_1!=1):
            prod *= cost_derivative(z[layers-1],y,m)
        prod = prod*prod_1*sigmoid_diff(z[i])
        prod *= sigmoid_diff(np.dot(weights[i-1],z[i-1]))
        prod1 = prod
        try:
            prod2 = prod*weights[i-1]*z[i-1].T
        except:
            prod2 = prod*z[i-1].T
        grad_cw[i-1] = lr[i-1]*prod2
    return grad_cw

In [406]:
layers,weights = network_structure([1,5,5,1])
learning_rates = [0.9,0.4,0.1] #for 3 weights matrices
x_input = x[0]
z = feedforward(x_input,weights)
learning_rate = 0.1

In [407]:
x = np.arange(0,100)
y = np.sin(x)

In [408]:
for i in range(len(x)):
    x_input=x[i]
    y1 = y[i]
    z = feedforward(x_input,weights)
    delta_cw = backprop(y1,1000,z,weights,learning_rates)       
    weights = np.add(weights,delta_cw)

In [409]:
delta_cw

[array([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.]]),
 array([[ 0.00144534,  0.0005656 ,  0.00121321,  0.00105145,  0.00192509],
        [ 0.00101198,  0.00185982,  0.00231802,  0.00055845,  0.00167806],
        [ 0.00058976,  0.00138825,  0.00168843,  0.00136367,  0.00199462],
        [ 0.00139701,  0.00107887,  0.00483113,  0.00107462,  0.00163189],
        [ 0.00245785,  0.00170383,  0.00176823,  0.00114411,  0.0003344 ]]),
 array([[ 0.00105512,  0.00045841,  0.00054367,  0.0003576 ,  0.00048886]])]

In [410]:
mean_squared_error = 0
pred = []
for i in range(len(x)):
    t = feedforward(x[i],weights)
    pred.append(t[-1])
    mean_squared_error += (y[i]-t[-1])**2
    mean_squared_error /= 1000

In [411]:
mean_squared_error

array([[ 0.0037919]])